version: '3.8'

networks:
  network:

volumes:
  mysql-data:

services:
  nebula-app:
    image: php:8.1-fpm
    container_name: nebula-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - network
    depends_on:
      - nebula-mysql
      - nebula-redis

  nebula-nginx:
    image: nginx:latest
    container_name: nebula-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx-config:/etc/nginx/conf.d
      - ./:/var/www/html
    networks:
      - network
    depends_on:
      - nebula-app

  nebula-mysql:
    image: mysql:8.0
    container_name: nebula-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.docker
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - network

  nebula-redis:
    image: redis:latest
    container_name: nebula-redis
    ports:
      - "6379:6379"
    env_file:
      - .env.docker
    networks:
      - network

